version: "2"

services:
  mysql:
    image: shop-mysql
    container_name: "shop-mysql"
    
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - "shop-db-volume:/var/lib/mysql"
    networks:
      - persist
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -p123456"]
      interval: 10s
      timeout: 5s
      retries: 3

  server:
    image: shop-server
    container_name: "shop-server"
    build: ./server
    ports:
      - "8888:8888"
    networks:
      - persist
    depends_on:
      mysql:
        condition: "service_healthy"

volumes:
  shop-db-volume:
networks:

  persist:
    external:
      name: vue-shop-net
